config/routes.rb
Rails.application.routes.draw do
  
  resources :events do 
    collection do 
      get :get_events
      post :move
      post :resize
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'
  get '/auth/login', to: 'sessions#login'
  
  
  resources :cas do
    get :get_ca_events
    
    resources :events, only: [:new]
  end
  
  resources :spreadsheets, only: [:index, :new, :create, :destroy]
  

  root 'events#index'

end

app/models/ca.rb
class Ca < ActiveRecord::Base
	has_many :timeslots
	validates :name, :email, :presence => true
	
	def self.get_by_email(email)
	    return find_by(email: email)
	end
	
	def self.get_by_user_id(id)
		return find_by(user_id: id)
	end
	 
end

app/controllers/c_as_controller.rb
class CAsController < ApplicationController
  before_action :set_ca, only: [:show, :edit, :update, :destroy]

  # GET /cas
  # GET /cas.json
  def index
    @cas = Ca.all
  end

  # GET /cas/1
  # GET /cas/1.json
  def show
  end

  # GET /cas/new
  def new
    @ca = Ca.new
  end

  # GET /cas/1/edit
  def edit
  end

  # POST /cas
  # POST /cas.json
  def create
    @ca = Ca.new(ca_params)

    respond_to do |format|
      if @ca.save
        format.html { redirect_to @ca, notice: 'Ca was successfully created.' }
        format.json { render :show, status: :created, location: @ca }
      else
        format.html { render :new }
        format.json { render json: @ca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cas/1
  # PATCH/PUT /cas/1.json
  def update
    respond_to do |format|
      if @ca.update(ca_params)
        format.html { redirect_to @ca, notice: 'Ca was successfully updated.' }
        format.json { render :show, status: :ok, location: @ca }
      else
        format.html { render :edit }
        format.json { render json: @ca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cas/1
  # DELETE /cas/1.json
  def destroy
    @ca.destroy
    respond_to do |format|
      format.html { redirect_to cas_url, notice: 'Ca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ca
      @ca = Ca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ca_params
      params.require(:ca).permit(:name, :email, :phone_number)
    end
end

app/controllers/cas_controller.rb
include EventsHelper
require_relative '../helpers/fetch_sheets.rb'

class CasController < ApplicationController
  include SessionsHelper
  before_action :set_ca, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  before_action :require_ca_login, only: [:show, :edit, :update]
  before_action :require_admin_login, only: [:index, :new, :create, :update, :destroy]
  
  def ca_params
    params.require(:ca).permit(:name, :email, :phone_number)
  end

  # GET /cas
  # GET /cas.json
  def index
    @ca = Ca.all
    
  end

  # GET /cas/1
  # GET /cas/1.json
  def show
  end

  # GET /cas/new
  def new
    @ca = Ca.new
  end

  # GET /cas/1/edit
  def edit

  end

  # POST /cas
  # POST /cas.json
  def create
    params.permit!
    if params[:ca][:name] == "" or params[:ca][:email] == ""  or params[:ca][:phone_number] == "" 
      flash[:error] = "Please do not leave any fields blank."
      redirect_to new_ca_path
      return
    end
    @ca = Ca.create(ca_params)
    
    if @ca.save
      redirect_to cas_path
    else
      redirect_to action: 'error'
    end
    
  end
  
  def error
  end

  # PATCH/PUT /cas/1
  # PATCH/PUT /cas/1.json
  def update
    params.permit!
    if params[:ca][:name] == "" or params[:ca][:email] == ""  or params[:ca][:phone_number] == ""
      flash[:error] = "Please do not leave any fields blank."
      redirect_to edit_ca_path
      return
    end
    respond_to do |format|
      if @ca.update(ca_params)
        format.html { redirect_to @ca, notice: 'Ca was successfully updated.' }
        format.json { render :show, status: :ok, location: @ca }
      else
        format.html { render :edit }
        format.json { render json: @ca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cas/1
  # DELETE /cas/1.json
  def destroy
    
    Event.destroy_all(:ca_id => @ca.id)
    timeslots = Timeslot.where(:ca_id => @ca.id)
    for ts in timeslots
      if ENV["TESTING_ENV"] == "false"
        # :nocov:
  			remove_name_from_spreadsheet(ts)
  			# :nocov:
  		end
    end
    Timeslot.destroy_all(:ca_id => @ca.id)
    @ca.destroy
    respond_to do |format|
      format.html { redirect_to cas_url, notice: 'Ca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  

  
  def get_ca_events
    ca_id = params[:ca_id]
    @events = Event.where(["start_time >= '#{Time.at(params['start'].to_i).to_formatted_s(:db)}' and end_time <= '#{Time.at(params['end'].to_i).to_formatted_s(:db)}'"] ).where(:ca_id => ca_id)
    events = make_event_json(@events, ca_id=ca_id) 
    render :text => events.to_json
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ca
      @ca = Ca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ca_params
      params.fetch(:ca, {})
    end
end

app/views/cas/_form.html.erb
<%= form_for(@ca) do |f| %>
  <% if @ca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ca.errors.count, "error") %> prohibited this ca from being saved:</h2>

      <ul>
      <% @ca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cas/create.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title add CA
    %link{:charset => "utf-8", :href => "cas.css", :media => "screen", :rel => "stylesheet"}/
  %body
    %button.buttons.button1{:type => "button"} CALENDAR
    %button.buttons.button2{:type => "button"} CA INFO
    %button.buttons.button3{:type => "button"} ADD CA
    %main
      %form
        %p{:style => "text-align: center; font-size: 20px"} CA INFO
        %label NAME:
        %br/
        %input{:name => "fullname", :type => "text"}/
        %br/
        %label EMAIL:
        %br/
        %input{:name => "email", :type => "text"}/
        %br/
        %label PHONE:
        %br/
        %input{:name => "phone", :type => "text"}/
        .center_buttons
          %button.buttons{:type => "button"} ADD
          %button.buttons{:type => "button"} CANCEL

app/views/cas/edit.html.haml
%center
  %main.header_block Edit info of CA
%br
= form_tag ca_path(@ca), :method => :put do

  = label :ca, :name, 'Name', :class => "edit_label"
  = text_field :ca, 'name'

  = label :ca, :email, 'Email', :class => "edit_label"
  = text_field :ca, 'email'
  
  = label :ca, :phone_number, 'Phone Number', :class => "edit_label"
  = text_field :ca, 'phone_number'
  %br
  =submit_tag 'Save', :class => "savebutton"
        
= button_to 'Delete', ca_path(@ca), :method => :delete, :confirm => 'Are you sure?', :class => "deletebutton"

app/views/cas/index.html.haml
%center
  %h2.header_block LIST of CA
%h4
  = link_to 'ADD CA', new_ca_path, class: "addButton", style: 'color: white;'
%br
%br
%br
%br
%table.myTable
  %thead
    %tr
      %th{:style => "padding:20px 150px 0px 15px;"} NAME
      %th{:style => "padding:20px 150px 0px 15px;"} EMAIL
      %th{:style => "padding:20px 150px 0px 15px;"} PHONE
      %th{:style => "padding:20px 50px 0px 15px"}
  %tbody
    - @ca.each do |item|
      %tr
        %td= item.name
        %td= item.email
        %td= item.phone_number
        %td= link_to "Details".html_safe, ca_path(item), class: "myButton"

app/views/cas/link.html.haml
%center
    %main.header_block Here's the link to the new spreadsheet!
    
=button_to 'CANCEL', cas_path, :method => :get, :class => "deletebutton"

app/views/cas/new.html.haml
%center
    %main.header_block Fill below to add new CA
= form_tag cas_path do

    = label :ca, :name, 'Name', :class => "edit_label"
    = text_field :ca, 'name'

    = label :ca, :email, 'Email', :class => "edit_label"
    = text_field :ca, 'email'

    = label :ca, :phone_number, 'Phone Number', :class => "edit_label"
    = text_field :ca, 'phone_number'
    %br
    = submit_tag 'Add', :class => "savebutton"
    
=button_to 'CANCEL', cas_path, :method => :get, :class => "deletebutton"

app/views/cas/show.html.erb
<h1>
  <%= @ca.name.inspect %>
</h1>
<h3> <%= @ca.email.inspect %> </h3>
<h3> <%= @ca.phone_number.inspect %> </h3>





<center>
<h1>Schedule</h1>

</center>
<br>
<p>
  <%= link_to 'Add Availability', new_ca_event_path(@ca), :id => 'new_event' %>
  <%= link_to 'Edit CA Info', edit_ca_path(@ca)  %>
  <%= link_to 'Back', cas_path %>
</p>

<script>
  
  
  $(document).ready(function(){
      // page is now ready, initialize the calendar...
      $('#new_event').click(function(event) {
        event.preventDefault();
        var url = $(this).attr('href');
        $.ajax({
          url: url,
          beforeSend: function() {
            $('#loading').show();
          },
          complete: function() {
            $('#loading').hide();
          },
          success: function(data) {
            $('#create_event').replaceWith(data['form']);
            $('#create_event_dialog').dialog({
              title: 'New Event',
              modal: true,
              width: 500,
              close: function(event, ui) { $('#create_event_dialog').dialog('destroy') }
            });
          }
        });
      });

      $('#calendar').fullCalendar({
          editable: true,
          header: {
              left: 'prev,next today',
              center: 'title',
              right: 'month,agendaWeek,agendaDay'
          },
          defaultView: 'agendaWeek',
          height: 500,
          slotMinutes: 15,
          loading: function(bool){
              if (bool) 
                  $('#loading').show();
              else 
                  $('#loading').hide();
          },
          events: "/events/get_ca_events",
          timeFormat: 'h:mm t{ - h:mm t} ',
          dragOpacity: "0.5",
          eventDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc){
//              if (confirm("Are you sure about this change?")) {
                  moveEvent(event, dayDelta, minuteDelta, allDay);
//              }
//              else {
//                  revertFunc();
//              }
          },
          
          eventResize: function(event, dayDelta, minuteDelta, revertFunc){
//              if (confirm("Are you sure about this change?")) {
                  resizeEvent(event, dayDelta, minuteDelta);
//              }
//              else {
//                  revertFunc();
//              }
          },
          
          eventClick: function(event, jsEvent, view){
              showEventDetails(event);
          },
      
      
      
      
      });
  });
</script>
<div>
  <div id='calendar'>
  </div>
</div>
<div id = "desc_dialog" class="dialog" style ="display:none;">
  <div id = "event_desc">
  </div>
  <br/>
  <br/>
  <div id = "event_actions">
    <span id = "edit_event"></span>
    <span id = "delete_event"></span>
  </div>
</div>
<div id = "create_event_dialog" class="dialog" style ="display:none;">
  <div id = "create_event">
  </div>
</div>

app/views/cas/show.html.haml
%center
  %h2.header_block
    %big Schedule for <em><b>#{@ca.name}</b></em>
  %br
  %br
%h3.info_block
  Email: #{@ca.email} 
  %br/
  Phone Number: #{@ca.phone_number}

%h4
  = link_to "Add Availability", new_ca_event_path(@ca), id: 'new_event', class: "addButton", style: 'color: white;'
  = link_to "Edit CA Info", edit_ca_path(@ca), class: "addButton", style: 'color: white;'

%body
  %p
    %div
      #calendar
    #desc_dialog.dialog{:style => "display:none;"}
      #event_desc
      %br/
      %br/
      #event_actions
        %span#edit_event.savebutton
        %span#delete_event.deletebutton
    #create_event_dialog.dialog{:style => "display:none;"}
      #create_event




:javascript  
  $(document).ready(function(){
      // page is now ready, initialize the calendar...
      var url = document.URL;
      var ca_id = url.substring(url.lastIndexOf('/') + 1);
      $('#new_event').click(function(event) {
        event.preventDefault();
        var url = $(this).attr('href');
        $.ajax({
          url: url,
          beforeSend: function() {
            $('#loading').show();
          },
          complete: function() {
            $('#loading').hide();
          },
          success: function(data) {
            $('#create_event').replaceWith(data['form']);
            $('#create_event_dialog').dialog({
              title: 'New Open House Schedule',
              modal: true,
              width: 400,
              close: function(event, ui) { $('#create_event_dialog').dialog('destroy') }
            });
          }
        });
      });

      $('#calendar').fullCalendar({
          defaultEventMinutes : 30,
          editable: true,
          header: {
              left: 'prev,next today',
              center: 'title',
              right: 'month,agendaWeek,agendaDay'
          },
          weekends: false,
          defaultView: 'month',
          slotMinutes: 30,
          aspectRatio: 1.5,
          disableResizing: true,
          defaultTimedEventDuration: '00:30:00',
          forceEventDuration: true,
          loading: function(bool){
              if (bool) 
                  $('#loading').show();
              else 
                  $('#loading').hide();
          },
          events: "/cas/"+ca_id+"/get_ca_events",
          timeFormat: 'h:mm t{ - h:mm t} ',
          dragOpacity: "0.5",
          eventDrop: function(event, dayDelta, minuteDelta, revertFunc){
                  moveEvent(event, dayDelta, minuteDelta);

          },
          
          eventClick: function(event, jsEvent, view){
            // change the border color just for fun
            $(this).css('border-color', 'red');
              showEventDetails(event);
          },
          eventRender: function (event, element) {
              element.find('.fc-event-title').append("  " + event.ca_name.toUpperCase()); 
          }
      
      });
  });