config/routes.rb
Rails.application.routes.draw do
  
  resources :events do 
    collection do 
      get :get_events
      post :move
      post :resize
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'
  get '/auth/login', to: 'sessions#login'
  
  
  resources :cas do
    get :get_ca_events
    
    resources :events, only: [:new]
  end
  
  resources :spreadsheets, only: [:index, :new, :create, :destroy]
  

  root 'events#index'

end

app/models/timeslot.rb
require_relative '../helpers/fetch_sheets.rb'

class Timeslot < ActiveRecord::Base
	belongs_to :ca
	validates_uniqueness_of :starttime

	after_create :write_spreadsheet

	def write_spreadsheet()
		if ENV["TESTING_ENV"] == "false"
			# :nocov:
			write_to_spreadsheet(self)
			# :nocov:
		end
	end
	
end

app/helpers/timeslot_helper.rb
require 'time'

module TimeslotHelper
	
	def add_30min(starttime)
		if starttime.nil?
			return nil
		end
		return starttime + 30*60
	end
	
end

app/views/timeslot/index.html.haml
%head
  = link_to 'CALENDAR', events_path, :class => 'buttons'
  = link_to 'CA INFO', cas_path, :class => 'buttons'
  = link_to 'ADD CA', new_ca_path, :class => 'buttons button3'

%body
  %p
    %div
      #timeslot
    
:javascript
    $(document).ready(function() {
      $("#timeslot").fullCalendar({
        header: {
          left: "prev,next today",
          center: "title",
          right: "month,agendaWeek,agendaDay,listDay"
        },
        theme: false,
        slotMinutes: 15,
        aspectRatio: 1.5,
        listDayFormat: true,
      })
    });