config/routes.rb
Rails.application.routes.draw do
  
  resources :events do 
    collection do 
      get :get_events
      post :move
      post :resize
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'
  get '/auth/login', to: 'sessions#login'
  
  
  resources :cas do
    get :get_ca_events
    
    resources :events, only: [:new]
  end
  
  resources :spreadsheets, only: [:index, :new, :create, :destroy]
  

  root 'events#index'

end

app/models/spreadsheet.rb
class Spreadsheet < ActiveRecord::Base
    validates :month, :year, :spreadsheet_id, :link, :presence => true
    

    def self.get_id_by_date(month, year)
        spreadsheet = find_by(month: month, year: year)
        if spreadsheet.nil?
            return nil
        end
        return spreadsheet.spreadsheet_id
    end
    

    
    
    
end

app/controllers/spreadsheets_controller.rb
require_relative '../helpers/fetch_sheets.rb'

class SpreadsheetsController < ApplicationController
    include SessionsHelper
    before_action :require_login
    before_action :require_admin_login, only: [:new, :create, :destroy]
    
    
    
    def index
        @spreadsheets = Spreadsheet.all
    end
    
    def new 
        @spreadsheet = Spreadsheet.new
    end
    

    def spreadsheet_exists(month, year)
        if Spreadsheet.get_id_by_date(month, year)
            return true
        end
        return false
    end
    
    def create
        year = params[:ca][:year].to_i
        month = params[:ca][:month].to_i
        if spreadsheet_exists(month, year)
            flash[:error] = "Spreadsheet for this month and year already exists"
            redirect_to new_spreadsheet_path
            return
        end
        if year.to_s.length != 4
            flash[:error] = "Please enter the year in YYYY format."
            redirect_to new_spreadsheet_path
            return
        end
        if month < 1 or month > 12
            flash[:error] = "Please enter a month from 1-12."
            redirect_to new_spreadsheet_path
            return
        end
        date = Date.new(year, month, 1)
        
        link = params[:ca][:link]
        spreadsheet_id = /\/spreadsheets\/d\/([a-zA-Z0-9\-_]+)/.match(link) 
        if !spreadsheet_id
            flash[:error] = "Invalid spreadsheet url"
            redirect_to new_spreadsheet_path
            return
        end
        spreadsheet_id = spreadsheet_id[1]
        
        @spreadsheet = Spreadsheet.new({:month => date.month, :year => date.year, :spreadsheet_id => spreadsheet_id, :link => link}) 
        if @spreadsheet.save
            populate_spreadsheet(date, link, spreadsheet_id)
            flash[:success] = "Spreadsheet has been created"
            redirect_to spreadsheets_path
        end
    end
    
    
    def destroy
        Spreadsheet.find(params[:id]).destroy
        flash[:notice] = "Spreadsheet was removed from this app, but still exists."
        redirect_to spreadsheets_path
    end
    
    private
        def spreadsheet_params
            params.require(:spreadsheet).permit('month', 'year', 'spreadsheet_id', 'link')
        end
        
    
end

app/views/spreadsheets/index.html.haml
%center
  %h2.header_block SPREADSHEETS
%h4
  = link_to 'ADD SPREADSHEET', new_spreadsheet_path, class: "addButton", style: 'color: white;'
  = link_to "VIEW TEMPLATE SHEET".html_safe, ENV['TEMPLATE_LINK'], class: "addButton", style: 'color: white;'
%br
%br
%br
%br
%table.myTable
  %thead
    %tr
      %th{:style => "padding:20px 150px 0px 15px;"} MONTH
      %th{:style => "padding:20px 150px 0px 15px;"} YEAR
      %th{:style => "padding:20px 150px 0px 15px;"}
      %th{:style => "padding:20px 150px 0px 15px;"}
  %tbody
    - @spreadsheets.each do |item|
      %tr
        %td= item.month
        %td= item.year
        %td= link_to "View".html_safe, item.link, class: "myButton"
        %td= button_to 'Remove', spreadsheet_path(item), :method => :delete, :confirm => 'Are you sure?', :class => "deletebutton"

app/views/spreadsheets/new.html.haml
%center
    %main.header_block Populate Spreadsheet
    %h2 Please input the month, year, and link of your newly created spreadsheet
= form_tag spreadsheets_path do

    = label :ca, :month, 'Month', :class => "edit_label"
    = text_field :ca, 'month'
    

    = label :ca, :year, 'Year', :class => "edit_label"
    = text_field :ca, 'year'
    
    = label :ca, :spreadsheet_url, 'New Spreadsheet Link', :class => "edit_label"
    = text_field :ca, 'link'

    %br
    = submit_tag 'Populate', :class => "savebutton"
    
=button_to 'CANCEL', spreadsheets_path, :method => :get, :class => "deletebutton"

app/views/spreadsheets/update_template.html.haml
%center
    %main.header_block UPDATE TEMPLATE SHEET
    %h2 If you would like to change the format of the spreadsheet, please make the changes to the template sheet. If you need to change the link to the template sheet, enter the new one below.
%center
    %h4 
        = link_to "Edit Template Sheet".html_safe, @template.link, class: "myButton"
%br
%br
%br
%br

= form_tag spreadsheets_path do

    = label :ca, :spreadsheet_url, 'New Spreadsheet Link', :class => "edit_label"
    = text_field :spreadsheet, 'spreadsheet_url'

    %br
    = submit_tag 'Save', :class => "savebutton"
    
=button_to 'Back', spreadsheets_path, :method => :get, :class => "deletebutton"