config/routes.rb
Rails.application.routes.draw do
  
  resources :events do 
    collection do 
      get :get_events
      post :move
      post :resize
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/logout', to: 'sessions#destroy'
  get '/auth/login', to: 'sessions#login'
  
  
  resources :cas do
    get :get_ca_events
    
    resources :events, only: [:new]
  end
  
  resources :spreadsheets, only: [:index, :new, :create, :destroy]
  

  root 'events#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.google.com", class="a_link">UCB Housing APP</a>
    by Team 15
  </small>
  <nav>
    <ul>
      <li><a href="http://www.google.com", class="a_link">Contact</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "UCB Family Housing", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <%= link_to "Sign out", '/auth/logout', {:style=>'color:#FFD700;'}%>
            </li>
          <% else %>
            <li id="fat-menu" class="dropdown">
              <%= link_to "Sign in", '/auth/google_oauth2',  {:style=>'color:#FFD700;'}%>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
<h1>
  <%= link_to 'CALENDAR', events_path, :class => 'columnButton'%>
  <%= link_to 'CA INFO', cas_path, :class => 'columnButton'%>
  <%= link_to 'SPREADSHEETS', spreadsheets_path, :class => 'columnButton'%>
</h1>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UC Berkeley Housing</title>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  </head>
  <body class="subpage">
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if not Rails.env.development? %>
    </div>
    
    
    <script type="text/javascript">
      authenticity_token = "<%= form_authenticity_token %>"
    </script>


  </body>
</html>